openapi: 3.1.0
info:
  title: User Management API
  version: 0.0.1
servers:
  - url: http://localhost:8080/usermanagement/api
    description: Local development server


paths:
  /ping:
    get:
      summary: Test endpoint for service availability
      description: A simple endpoint to check if the user management service is running.
      responses:
        '200':
          description: Service is running
          content:
            text/plain:
              schema:
                type: string
                example: "pong"
        '500':
          description: Internal server error
        '503':
          description: Service unavailable

  /user:
    post:
      summary: Create a new user
      description: Create a new user in the database.
      requestBody:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/User'
                  - type: object
                    properties:
                      password:
                      type: string
                      format: password
                      description: The user's password.
                    required:
                      - email
                      - password
                      - first_name
                      - last_name
                      - age
                      - sex
                      - height_in
                      - weight_lbs
      responses:
        '201':
          description: User created successfully
        '400':
          description: Bad request - invalid input
        '409':
          description: Conflict - user already exists
        '500':
          description: Internal server error
        '503':
          description: Service unavailable
        '507':
          description: Insufficient storage
    patch:
      summary: Update an existing user
      description: Update an existing user's information in the database.
      requestBody:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/User'
                  - type: object
                    required:
                      - email
      responses:
        '200':
          description: User updated successfully
        '400':
          description: Bad request - invalid input
        '401':
          description: Unauthorized - authentication failed
        '404':
          description: Not found - user does not exist
        '500':
          description: Internal server error
        '503':
          description: Service unavailable
    
  /user/{email}:
    delete:
      summary: Delete a user
      description: Delete a user from the database by their email address.
      parameters:
        - name: email
          in: path
          required: true
          description: The email address of the user to delete.
          schema:
            type: string
            format: email
      responses:
        '200':
          description: User deleted successfully
        '400':
          description: Bad request - invalid email format
        '401':
          description: Unauthorized - authentication failed
        '404':
          description: Not found - user does not exist
        '500':
          description: Internal server error
        '503':
          description: Service unavailable

  /profile/{email}:
    get:
      summary: Retrieve user medical profile information
      description: Retrieve medical profile information for a user by their email address.
      parameters:
        - name: email
          in: path
          required: true
          description: The email address of the user whose profile to retrieve.
          schema:
            type: string
            format: email
      responses:
        '200':
          description: User medical profile retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
        '400':
          description: Bad request - invalid email format
        '401':
          description: Unauthorized - authentication failed
        '404':
          description: Not found - user does not exist
        '500':
          description: Internal server error
        '503':
          description: Service unavailable


components:
  schemas:
    User:
      type: object
      properties:
        email:
          type: string
          format: email
          description: The user's email address.
        first_name:
          type: string
          description: The user's first name.
        last_name:
          type: string
          description: The user's last name.
        age:
          type: integer
          description: The user's age.
          minimum: 0
          exclusiveMinimum: true
          maximum: 150
        sex:
          type: string
          description: The user's sex assigned at birth.
          enum: ['male', 'female']
        gender_identity:
          type: string
          description: The user's gender identity.
        height_in:
          type: number
          format: float
          minimum: 0
          exclusiveMinimum: true
          description: The user's height in inches.
        weight_lbs:
          type: number
          format: float
          minimum: 0
          exclusiveMinimum: true
          description: The user's weight in pounds.

    Profile:
      type: object
      properties:
        first_name:
          type: string
          description: The user's first name.
        last_name:
          type: string
          description: The user's last name.
        age:
          type: integer
          description: The user's age.
          minimum: 0
          exclusiveMinimum: true
          maximum: 150
        sex:
          type: string
          description: The user's sex assigned at birth.
          enum: ['male', 'female']
        gender_identity:
          type: string
          description: The user's gender identity.
        height_in:
          type: number
          format: float
          minimum: 0
          exclusiveMinimum: true
          description: The user's height in inches.
        weight_lbs:
          type: number
          format: float
          minimum: 0
          exclusiveMinimum: true
          description: The user's weight in pounds.
      required:
        - first_name
        - last_name
        - age
        - sex
        - height_in
        - weight_lbs
